# GET http://localhost:4004/odata/v4/admin/Books


POST http://localhost:4004/odata/v4/admin/Books
Content-Type: application/json

{
      "ID": 3,
      "title": "BTP Mentor",
      "stock": 95,
      "prices": 100
    }

# DELETE http://localhost:4004/odata/v4/admin/Books/3
